name: build
on: [ push, pull_request ]

env:
  MIN_JVM: 11
  MAX_JVM: 16

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 16 ]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.job }}-${{ matrix.java }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run tests
        run: ./gradlew assemble test
      - name: Publish Snapshot
        if: >
          matrix.java == env.MIN_JVM
          && github.event_name == 'push'
          && endsWith(github.ref, github.event.repository.default_branch)
        env:
          NEXUS_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: 241134EA
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: ./gradlew publishToSonatype